apiVersion: v1
kind: ConfigMap
metadata:
  name: http-simple-env
  namespace: http-simple
data:
  HTTP_SIMPLE_SERVER_PORT: "3000"
  HTTP_SIMPLE_TEST: "foobar"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: http-simple-certificate
  namespace: http-simple
data:
  certificate.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDXzCCAkegAwIBAgILBAAAAAABIVhTCKIwDQYJKoZIhvcNAQELBQAwTDEgMB4G
    A1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjMxEzARBgNVBAoTCkdsb2JhbFNp
    -----END CERTIFICATE-----
